# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UzTncF0wcBXoQV3-nWj21F4cS6RXztd
"""

import streamlit as st
import math

# Таблицы скидок (одинаковые для обеих услуг)
discount_table = [
    {'share': 0, 'mattress_count': 0, 'discount': 0.0377},
    {'share': 0.01, 'mattress_count': 37.01293661, 'discount': 0.0464},
    {'share': 0.02, 'mattress_count': 74.02587322, 'discount': 0.0524},
    {'share': 0.03, 'mattress_count': 111.0388098, 'discount': 0.0571},
    {'share': 0.04, 'mattress_count': 148.0517464, 'discount': 0.0611},
    {'share': 0.05, 'mattress_count': 185.0646831, 'discount': 0.0645},
    {'share': 0.06, 'mattress_count': 222.0776197, 'discount': 0.0675},
    {'share': 0.07, 'mattress_count': 259.0905563, 'discount': 0.0703},
    {'share': 0.08, 'mattress_count': 296.1034929, 'discount': 0.0728},
    {'share': 0.09, 'mattress_count': 333.1164295, 'discount': 0.0752},
    {'share': 0.10, 'mattress_count': 370.1293661, 'discount': 0.0774},
    {'share': 0.11, 'mattress_count': 407.1423027, 'discount': 0.0794},
    {'share': 0.12, 'mattress_count': 444.1552393, 'discount': 0.0813},
    {'share': 0.13, 'mattress_count': 481.1681759, 'discount': 0.0832},
    {'share': 0.14, 'mattress_count': 518.1811125, 'discount': 0.0849},
    {'share': 0.15, 'mattress_count': 555.1940492, 'discount': 0.0866},
    {'share': 0.16, 'mattress_count': 592.2069858, 'discount': 0.0882},
    {'share': 0.17, 'mattress_count': 629.2199224, 'discount': 0.0897},
    {'share': 0.18, 'mattress_count': 666.232859, 'discount': 0.0911},
    {'share': 0.19, 'mattress_count': 703.2457956, 'discount': 0.0926},
    {'share': 0.20, 'mattress_count': 740.2587322, 'discount': 0.0926}
]

def calculate_k2(mattress_count):
    """Расчет коэффициента скидки k2 на основе количества матрасов (точная логика Excel)"""
    d = mattress_count / 3701
    rounded_d = math.ceil(d * 100) / 100  # ОКРУГЛВВЕРХ(d;2)

    # Находим строку с rounded_d в таблице
    found_row = None
    for row in discount_table:
        if abs(row['share'] - rounded_d) < 0.0001:
            found_row = row
            break

    if found_row is None:
        return 0.0377  # Значение по умолчанию

    # ВПР(ОКРУГЛВВЕРХ(d;2);A29:C49;2;0) < mattress_count
    if found_row['mattress_count'] < mattress_count:
        return found_row['discount']
    else:
        # Ищем предыдущую строку (ИНДЕКС(C29:C49; ПОИСКПОЗ(ОКРУГЛВВЕРХ(d;2);A29:A49;0)-1))
        current_index = discount_table.index(found_row)
        if current_index > 0:
            return discount_table[current_index - 1]['discount']
        else:
            return found_row['discount']

def calculate_k1(time_to_departure):
    """Расчет коэффициента k1"""
    return 1 + 0.15 * (105 - time_to_departure) / 105

def calculate_k3(distance, mattress_count):
    """Расчет коэффициента k3 для утилизации"""
    base_k3 = 500 + (max(0, distance - 1000) * 0.5)

    # Добавляем 26 рублей за км на каждый матрас
    if mattress_count > 0:
        return base_k3 + (26 * distance)
    return base_k3

# ФИКСИРОВАННАЯ СТАНДАРТНАЯ ЦЕНА
STANDARD_PRICE = 1600

# Настройка страницы
st.set_page_config(
    page_title="Калькулятор стоимости услуг",
    page_icon="📊",
    layout="wide"
)

# CSS для кастомизации - УБРАНА ПАНЕЛЬ, ДОБАВЛЕН СДВИГ ВВЕРХ
st.markdown("""
<style>
    /* Белый цвет для всех текстов в основной области */
    .main .block-container {
        color: #ffffff;
    }

    /* Белый цвет для всех заголовков и текста */
    .main-header, .section-header, .stRadio label, .stSlider label,
    .stNumberInput label, .stExpander label, .stMarkdown, .stText {
        color: #ffffff !important;
    }

    /* Заголовок приложения */
    .main-header {
        font-size: 32px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 30px;
    }

    /* Заголовки секций */
    .section-header {
        font-size: 18px;
        font-weight: bold;
        margin-bottom: 15px;
    }

    /* Контейнер для результатов - БЕЗ ПАНЕЛИ, СДВИГ ВВЕРХ */
    .results-container {
        display: flex !important;
        flex-direction: column !important;
        justify-content: center !important;
        align-items: center !important;
        height: 400px !important;
        margin-top: -80px !important;
    }

    /* Черный цвет для текста результатов */
    .results-container * {
        color: #000000 !important;
    }

    /* Заголовок итоговой стоимости */
    .final-price-header {
        font-size: 28px !important;
        font-weight: bold !important;
        text-align: center !important;
        margin-bottom: 30px !important;
    }

    /* Отображение цены */
    .price-display {
        font-size: 72px !important;
        font-weight: bold !important;
        text-align: center !important;
        margin: 0 !important;
    }

    /* Сайдбар - белый текст */
    .css-1d391kg, .sidebar .stMarkdown, .sidebar .stText {
        color: #ffffff !important;
    }
</style>
""", unsafe_allow_html=True)

# Заголовок приложения (белый)
st.markdown('<div class="main-header">Калькулятор стоимости услуг</div>', unsafe_allow_html=True)

col1, col2 = st.columns([1, 1])

with col1:
    # Тип услуги (белые надписи)
    st.markdown('<div class="section-header">Тип услуги:</div>', unsafe_allow_html=True)
    service_type = st.radio(
        "Выберите тип услуги:",
        options=['Замена матрасов', 'Утилизация матрасов'],
        index=0
    )

    # Количество матрасов (белые надписи)
    st.markdown('<div class="section-header">Количество матрасов:</div>', unsafe_allow_html=True)
    mattress_count = st.slider(
        "Выберите количество матрасов:",
        min_value=0,
        max_value=3701,
        value=100,
        step=1
    )

    # Расстояние (белые надписи)
    st.markdown('<div class="section-header">Расстояние от Коврова (км):</div>', unsafe_allow_html=True)
    distance = st.slider(
        "Выберите расстояние:",
        min_value=1,
        max_value=2000,
        value=100,
        step=1
    )

    # Время до отправления (белые надписи) - теперь максимум 105 дней
    st.markdown('<div class="section-header">Время до отправления (дни):</div>', unsafe_allow_html=True)
    time_to_departure = st.slider(
        "Выберите количество дней:",
        min_value=0,
        max_value=105,
        value=30,
        step=1
    )

with col2:
    # Блок с результатами - БЕЗ ПАНЕЛИ, СДВИГ ВВЕРХ
    st.markdown("""
    <div class="results-container">
    """, unsafe_allow_html=True)

    # Расчет цены
    k1 = calculate_k1(time_to_departure)
    k2 = calculate_k2(mattress_count)

    if service_type == 'Замена матрасов':
        # Тариф = Ст.цена * k1 * (1-k2) + Расстояние * 0
        final_price = STANDARD_PRICE * k1 * (1 - k2)
    else:
        # Утилизация: Тариф = Ст.цена * k1 * (1-k2) + k3
        k3 = calculate_k3(distance, mattress_count)
        final_price = STANDARD_PRICE * k1 * (1 - k2) + k3

    formatted_price = f"{final_price:,.0f} ₽".replace(",", " ")

    # Заголовок и цена - черные и сдвинуты вверх
    st.markdown('<div class="final-price-header">ИТОГОВАЯ СТОИМОСТЬ</div>', unsafe_allow_html=True)
    st.markdown(f'<div class="price-display">{formatted_price}</div>', unsafe_allow_html=True)

    st.markdown("</div>", unsafe_allow_html=True)

# Информация о введенных значениях (белые надписи)
with st.sidebar:
    st.markdown("### Текущие параметры:")
    st.write(f"**Услуга:** {service_type}")
    st.write(f"**Матрасы:** {mattress_count} шт")
    st.write(f"**Расстояние:** {distance} км")
    st.write(f"**Дней до отправления:** {time_to_departure}")

    # Детали расчета
    with st.expander("Детали расчета"):
        st.write(f"**Коэффициент времени (k1):** {k1:.4f}")
        st.write(f"**Коэффициент скидки (k2):** {k2:.4f}")
        if service_type == 'Утилизация матрасов':
            k3_value = calculate_k3(distance, mattress_count)
            st.write(f"**Коэффициент утилизации (k3):** {k3_value:.2f} ₽")
        st.write(f"**Базовая цена:** {STANDARD_PRICE} ₽")
        st.write(f"**Доля от объема (d):** {(mattress_count / 3701):.4f}")
        st.write(f"**Округленная доля:** {math.ceil((mattress_count / 3701) * 100) / 100:.2f}")